RandomForestClassifier:
  n_estimators: 300           # Number of trees in the forest(100,200,300,500,1000)
  criterion: gini             # Criterion for splitting nodes ('gini' or 'entropy')
  max_depth: 10                # Maximum depth of the tree. None means unlimited depth.(5,10,20,50,100)
  min_samples_split: 4        # Minimum number of samples required to split an internal node(2,4,8,16,32,64)
  min_samples_leaf: 2         # Minimum number of samples required to be at a leaf node(1,2,5,10)